Repository campaignzero/police-scorecard, pull requests merged in 2020-09, with the labels that each got.

#20 Add header nav link for 'Contribute Data' form.
  resources/views/components/partial/menu.blade.php
Labels: In Code Review

#18 Open 'Contribute Data' form when users click on 'Add New Data' button.
  resources/assets/sass/_section.scss
  resources/views/components/partial/grades.blade.php
Labels: In Code Review

#25 Incorrect CSS Class Names for Deaths in Jail Chart
  resources/views/components/partial/jail/chart-deaths-in-jail.blade.php
Labels: Ready For Code Review

#23 Fix inconsistent sorting of department scores
  app/Helpers.php
  app/View/Components/Partial/Grades.php
  routes/web.php
Labels: Closed & Merged

#22 Update Sheriff Map
  resources/assets/js/home.js
  resources/assets/sass/_highcharts.scss
Labels: Closed & Merged
